apiVersion: v1
kind: Service
metadata:
  name: frontend-next-service
  namespace: ambient-code
  labels:
    app: frontend-next
spec:
  type: NodePort
  selector:
    app: frontend-next
  ports:
  - port: 3000
    targetPort: http
    nodePort: 30031
    protocol: TCP
    name: http
